remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Dr. Jaclyn Torkelson]
description: [PhD in environmental chemistry (marine biogeochemistry) from State University of New York College of Environmental Science and Forestry]
